title=Nations Gestions Mod
name=nations_gestions
author=Survivalier
version=1.0
<<<<<<< HEAD
description=A mod for Nations gestions
depends=sfinv
=======
description=A mod for Nations gestions
>>>>>>> d7dcc66 (update)
