name = invisiblocks
title = Invisiblocks
description = Add invisible barrier, light and mob wall into game
optional_depends = default, mcl_core
min_minetest_version = 5.0
release = 36297
author = TenPlus1
